module.exports = [
  {
    id: 1,
    name: "Ali Ahmadi",
    email: "ali.ahmadi@example.com",
    password: "password1",
  },
  {
    id: 2,
    name: "Sara Mohammadi",
    email: "sara.mohammadi@example.com",
    password: "password2",
  },
  {
    id: 3,
    name: "Reza Karimi",
    email: "reza.karimi@example.com",
    password: "password3",
  },
  {
    id: 4,
    name: "Niloofar Shabani",
    email: "niloofar.shabani@example.com",
    password: "password4",
  },
  {
    id: 5,
    name: "Hossein Jafari",
    email: "hossein.jafari@example.com",
    password: "password5",
  },
  {
    id: 6,
    name: "Maryam Heidari",
    email: "maryam.heidari@example.com",
    password: "password6",
  },
  {
    id: 7,
    name: "Farhad Ghasemi",
    email: "farhad.ghasemi@example.com",
    password: "password7",
  },
  {
    id: 8,
    name: "Fatemeh Ebrahimi",
    email: "fatemeh.ebrahimi@example.com",
    password: "password8",
  },
  {
    id: 9,
    name: "Amir Hosseini",
    email: "amir.hosseini@example.com",
    password: "password9",
  },
  {
    id: 10,
    name: "Leila Maleki",
    email: "leila.maleki@example.com",
    password: "password10",
  },
  {
    id: 11,
    name: "Parisa Yazdani",
    email: "parisa.yazdani@example.com",
    password: "password11",
  },
  {
    id: 12,
    name: "Saeed Kaviani",
    email: "saeed.kaviani@example.com",
    password: "password12",
  },
  {
    id: 13,
    name: "Mehdi Ranjbar",
    email: "mehdi.ranjbar@example.com",
    password: "password13",
  },
  {
    id: 14,
    name: "Shirin Nasiri",
    email: "shirin.nasiri@example.com",
    password: "password14",
  },
  {
    id: 15,
    name: "Pouya Bahrami",
    email: "pouya.bahrami@example.com",
    password: "password15",
  },
  {
    id: 16,
    name: "Zahra Sadat",
    email: "zahra.sadat@example.com",
    password: "password16",
  },
  {
    id: 17,
    name: "Arash Vaziri",
    email: "arash.vaziri@example.com",
    password: "password17",
  },
  {
    id: 18,
    name: "Narges Golkar",
    email: "narges.golkar@example.com",
    password: "password18",
  },
  {
    id: 19,
    name: "Hamed Rostami",
    email: "hamed.rostami@example.com",
    password: "password19",
  },
  {
    id: 20,
    name: "Elaheh Zandi",
    email: "elaheh.zandi@example.com",
    password: "password20",
  },
];
